export { default } from "./src/wallet-manager-multisig-squads.js";
export { default as WalletAccountMultisigSquads, PERMISSION } from "./src/wallet-account-multisig-squads.js";
export type MultisigInfo = import("@tetherto/wdk-wallet/multisig").MultisigInfo;
export type MultisigProposal = import("@tetherto/wdk-wallet/multisig").MultisigProposal;
export type MultisigInteractionResult = import("@tetherto/wdk-wallet/multisig").MultisigInteractionResult;
export type MultisigTransactionOptions = import("@tetherto/wdk-wallet/multisig").MultisigTransactionOptions;
export type MultisigOptions = import("@tetherto/wdk-wallet/multisig").MultisigOptions;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type SimpleSolanaTransaction = import("@tetherto/wdk-wallet-solana").SimpleSolanaTransaction;
export type SolanaTransactionReceipt = import("@tetherto/wdk-wallet-solana").SolanaTransactionReceipt;
export type MultisigSquadsWalletSigningConfig = import("./src/wallet-account-read-only-multisig-squads.js").MultisigSquadsWalletSigningConfig;
export type MultisigSquadsWalletConfig = import("./src/wallet-account-read-only-multisig-squads.js").MultisigSquadsWalletConfig;
export type MultisigSquadsWalletReadOnlyConfig = import("./src/wallet-account-read-only-multisig-squads.js").MultisigSquadsWalletReadOnlyConfig;
export type MultisigSquadsInfo = import("./src/wallet-account-read-only-multisig-squads.js").MultisigSquadsInfo;
export type MultisigSquadsProposal = import("./src/wallet-account-read-only-multisig-squads.js").MultisigSquadsProposal;
export type MultisigSquadsProposalResult = import("./src/wallet-account-multisig-squads.js").MultisigSquadsProposalResult;
export type MultisigSquadsTransactionOptions = import("./src/wallet-account-multisig-squads.js").MultisigSquadsTransactionOptions;
export type MultisigSquadsAddOwnerOptions = import("./src/wallet-account-multisig-squads.js").MultisigSquadsAddOwnerOptions;
export type MultisigCoordinatorFactory = import("./src/coordinators/index.js").MultisigCoordinatorFactory;
export type SquadsMember = import("./src/wallet-account-read-only-multisig-squads.js").SquadsMember;
export type SquadsMultisigAccount = import("./src/wallet-account-read-only-multisig-squads.js").SquadsMultisigAccount;
export type SquadsProposalAccount = import("./src/wallet-account-read-only-multisig-squads.js").SquadsProposalAccount;
export type SquadsAddressTableLookup = import("./src/wallet-account-read-only-multisig-squads.js").SquadsAddressTableLookup;
export type SquadsTransactionMessage = import("./src/wallet-account-read-only-multisig-squads.js").SquadsTransactionMessage;
export type SquadsTransactionKind = import("./src/wallet-account-read-only-multisig-squads.js").SquadsTransactionKind;
export type SquadsConfigActionKind = import("./src/wallet-account-read-only-multisig-squads.js").SquadsConfigActionKind;
export type SquadsConfigAction = import("./src/wallet-account-read-only-multisig-squads.js").SquadsConfigAction;
export type SquadsTransactionAccount = import("./src/wallet-account-read-only-multisig-squads.js").SquadsTransactionAccount;
export type SquadsProgramConfig = import("./src/wallet-account-read-only-multisig-squads.js").SquadsProgramConfig;
export type SquadsProposalContext = import("./src/wallet-account-read-only-multisig-squads.js").SquadsProposalContext;
export { default as WalletAccountReadOnlyMultisigSquads, PROPOSAL_DATA_MASK, SQUADS_PROGRAM_ADDRESS, TRANSACTION_KIND } from "./src/wallet-account-read-only-multisig-squads.js";
export { IMultisigCoordinator } from "./src/coordinators/index.js";
export { AccountNotOwnerError, ThresholdNotMetError } from "@tetherto/wdk-wallet/multisig";
export { AssertionError, InvalidTokenError, MaximumFeeExceededError, NoSuchElementError, NotImplementedError, ProviderError, ProviderErrorReason, ProviderRequiredError, UnsupportedOperationError, ValueError, WdkError } from "@tetherto/wdk-wallet";
